@startuml

hide empty methods

class Usager #LightPink

class Decision #LightYellow

class DroitPrestation #LightYellow

class Evenement #LightYellow

class Reservation #Thistle {
    type : Code [0..1]
    dateDepot : Date [0..1]
    dateAdmissionPrevue : Date [0..1]
    etablissementSouhaite : [0..*]
}

class Sejour #Thistle {
    idSejour : Identifiant [1..1]
    numeroDossierAdministratifSejour : Identifiant [0..1]
    ESSMSAccueil : EntiteJuridique [1..1]
    numeroDossierESSMSProvenance : Identifiant [0..1]
    ESSMSProvenance : EntiteJuridique [0..1]
    dateEntreeESSMSProvenance : DateHeure [0..1]
    dateAdmission : DateHeure [0..1]
    dateEntreePrevisionnelle : DateHeure [0..1]
    dateEntree : DateHeure [0..1]
    modaliteEntree : Code [0..1]
    libelleModeEntree : Texte [0..1]
    dateSortiePrevisionnelle : DateHeure [0..1]
    dateSortie : DateHeure [0..1]
    modaliteSortie : Code [0..1]
    libelleModeSortie : Texte [0..1]
    origineDemande : Texte [0..1]
    modaliteAccueil : Code [0..1]
    commentaire : Texte [0..1] 
}

class Inventaire #Thistle { 
    trousseau : texte [0..1]
}

class Solde #Thistle {
    dateSoldeFinal : Date [0..1]
    soldeFinalDepense : Montant [0..1]
    soldeFinalDepense : Montant [0..1]
    dateSoldeJour : Date [0..1]
    soldeFinalRecette : Montant [0..1]
    soldeFinalRecette : Montant [0..1]
}

class Contrat #Thistle {
    libellePrestation : Texte [0..1]
    prixUnitaire : Montant [0..1]
    tauxTVA : Mesure [0..1]
    dateEffet : Date [0..1]
    termePaiement : Indicateur  [0..1]
}

Usager "1" -- "*" Decision
Decision "1" -- "0..1" DroitPrestation
Reservation "*" - "1" DroitPrestation
Reservation "1" - "*" Usager
DroitPrestation "1" -- "*" Sejour
Sejour "1" -- "0..1" Inventaire
Sejour "1" - "*" Solde
Sejour "*" -- "*" Contrat
Usager "1" - "*" Sejour
Evenement "*" -- "0..1" Sejour
Usager "1" -- "*" Evenement

@enduml