@startuml

hide empty methods

class Usager #LightPink

class EntiteJuridique #LightGray
class StructureAccueil #LightYellow

class AssuranceMaladieComplementaire #LightYellow {
    numeroContrat : Identifiant [0..1]
    ouvrantDroit : Identifiant [0..1]
    ayantsDroit : Identifiant [0..*]
    nomOrganisme : Texte [0..1]
    libelleOrganisme : Texte [0..1]
    dateDebutDroit : Date [0..1]
    dateFinDroit : Date [0..1]
    aideComplementaireSante : Indicateur [0..1]
    typeFinDroit : Code [0..1]

}

class AssuranceMaladieObligatoire #LightYellow {
    ouvrantDroit : Identifiant [0..1]
    ayantsDroit : Identifiant [0..*]
    nomOrganisme : Texte [0..1]
    numeroCodeOrganisme : Identifiant [0..1]
    adresseOrganisme : Adresse [0..1]
    codeRisque : Code [0..1]
    dateDebutDroit : Date [0..1]
    dateFinDroit : Date [0..1]
    ticketModerateur : Texte [0..1]
    dateFinCentPourCent : Date [0..1]
    dateFinDroitPUMa : Date [0..1]
    droitPUMa : Indicateur [0..1]
}

class DemandeOrientation #LightYellow {
    idDemandeOrientation : Identifiant [1..1]
    typeDemande : Code [0..1] 
    natureDemande : Code [0..1] 
    demandeOrientation : ObjetBinaire [0..*]
    depotPoste : ObjetBinaire [0..1]
    dateEnvoiDemande : Date [0..1]
    reponseOrientation : ObjetBinaire [0..1]
    dateReponseOrientation : Date [0..1]
    pieceComplementaire : ObjetBinaire [0..*]
}

class Decision #LightYellow {
    idDecision : Identifiant [1..1]
    numeroEnregistrement : Identifiant [0..1]
    typeDecision : Code [1..1]
    dateEffetCloture : Date [0..1]
    idDecisionMAJ : Identifiant [0..*]
    idNat_Decision : Identifiant [0..1]
    dateDecision : Date [0..1]
    motivation : Code [0..*]
    motivationLocale : Texte [0..*]
    commentaire : Texte [0..1]
}

class DroitPrestation #LightYellow {
    idDroitPrestation : Identifiant [1..1]
    numeroAllocataire : Identifiant [0..1]
    categorieDroitPrestation : Code [1..1]
    typeDroitPrestation : Code [1..1]
    natureDroitPrestation : Code [1..1]
    dateOuverture : Date [1..1]
    dateEcheance : Date [1..1]
    existencePAG : Indicateur [1..1]
    motifFinPAG : Code [0..1]
    creton : Indicateur [0..1]
    taux : Mesure [0..1] 
    typeCompensation : Code [0..1]
    commentaire : Texte [0..1]
}

class DetailPrestation #LightYellow {
    temporaliteAccueil : Code [0..1]
    precisionOrientation : ConceptCode [0..1]
    accueilSequentiel : Indicateur [0..1]
    formation : Texte [0..1]
    montantAttribue : Montant [0..1]
    frequence : Mesure [0..1]
    qualificationOrientation : Code [1..1]
}

class PriseCharge #LightYellow {
    modePriseCharge : Code [0..1]
}

class Quantification #LightYellow {
    valeurPriseCharge : Numerique [0..1]
    UnitePriseCharge : Mesure [0..1]
    frequencePriseCharge : Code [0..1]
}

Decision "*" -- "1" Usager
DemandeOrientation "*" - "1" Usager

DemandeOrientation "1" -- "*" Decision

Decision "1" -- "0..1" DroitPrestation

DroitPrestation "1" -- "1" DetailPrestation
EntiteJuridique <|-- StructureAccueil
DetailPrestation "1" - "*" StructureAccueil
DetailPrestation "1" -- "*" PriseCharge
PriseCharge "1" -- "0..1" Quantification

Usager "1" -- "0..1"  AssuranceMaladieComplementaire
Usager "1" - "1" AssuranceMaladieObligatoire
@enduml