@startuml

hide empty methods

class Usager #LightPink

class Contact #LightBlue {
    role : Code [0..1]
    description : Texte [0..1]
    relation : Code [0..1]
    }


class PersonnePhysique #LightBlue {
    identifiantPP : Identifiant [1..1]
    nomNaissance : Texte [0..1]
    prenom : Texte [0..*]
    civilite : Code [0..1]
    sexe : Code [0..1]
    paysNationalite : Code [0..*]
    dateNaissance : Date [0..1]
    adresse : Adresse [0..1]
    telecommunication : Telecommunication [0..*]
    commentaire : Texte [0..1]
}

class MesureProtection #LightBlue {
    typeMesureProtection : Code [0..1]
    nom : Texte [0..1]
    prenom : Texte [0..1]
    dateFin : Date [0..1]
    adresse : Adresse [0..1]
    telecommunication : Telecommunication [0..*]
    commentaire : Texte [0..1]
}

class MobiliteUsager #LightBlue {
    type : Code [0..1]
    observationAmenagement : Texte [0..1]
}

class PermisConduire #LightBlue {
    numPermisConduire : Identifiant [0..1]
    categorie : Code [0..1]
    dateObtention : Date [0..1]
    dateValidite : Date [0..1]
}

class Ressource #LightBlue {
    type : Code [0..1]
    contactOrganisme :  ContactPersonneMorale  [0..1]
    montant : Montant [0..1]
    frequence : Mesure [0..1]
    dateDebut : Date [0..1]
    dateFin : Date [0..1]
    pieceJointe : ObjetBinaire [0..*]
    idDroitPrestation : Identifiant [0..1]
}

class CompteBancaire #LightBlue {
    adresseBanque :  Adresse [0..1]
    identifiantBanque : Identifiant [0..1]
    identifiantGestionnaire : Identifiant [0..1]
    dateSouscription : Date [0..1]
    dureeSouscription : Mesure [0..1]
    dateOuverture : Date [0..1]
    dateEcheance : Date [0..1]
    dateFinPropagation : Date [0..1]
    dateCloture : Date [0..1]
    domiciliationBancaire : Indicateur [0..1]
    echeanceRevenus : Date [0..1]
    type : Code [0..1]
    RIB : RIB [0..1]
}

Contact "*" -- "1" Usager
PersonnePhysique "1" -- "1" Contact

PermisConduire "*" - "1" Usager 
Usager"1" - "*" MobiliteUsager 
Usager "1" -- "*" MesureProtection
Usager "1" -- "*" CompteBancaire
Usager "1" -- "*" Ressource

@enduml