@startuml

map "**EntiteJuridique : TDDUIOrganization**" as EntiteJuridique #back:LightGoldenRodYellow;header:Gold {
    idNat_Struct => <&layers> identifier:idNatSt
    raisonSocial => name
}


@enduml