@startuml

map "executionPeriod" as executionPeriod #DarkGray {
    dateDebutAction => start
    dateFinAction => end
}

object "**TDDUICarePlanProjetPersonnalise**" as TDDUICarePlanProjetPersonnalise_basedOn #8dd3c7 {
    ProjetPersonnalise
}

map "**Action : TDDUITaskAction**" as Action #d9d9d9 {
    idAction => identifier
    statutAction.statut => status
    statutAction.dateStatut => meta.lastUpdated
    statutAction.auteur => <&plus> auteurStatut
    descriptionAction => description
    referentAction => owner
    titreAction => <&layers> input:titre
    evaluationAction => <&layers> input:evaluation
    avisUsagerAction => <&layers> input:avisUsager
    resultatAttenduAction => <&layers> input:resultatAttendu
    pieceJointeAction => <&layers> input:pieceJointe
    Objectif => <&layers> input:objectif
    executionPeriod *-> executionPeriod
}

Action -u-> TDDUICarePlanProjetPersonnalise_basedOn : basedOn

@enduml