@startuml

map "executionPeriod" as executionPeriod #DarkGray {
    dateDebutPrestation => start
    dateFinPrestation => end
}

object "**TDDUICarePlanProjetPersonnalise**" as TDDUICarePlanProjetPersonnalise_basedOn #8dd3c7 {
    ProjetPersonnalise
}

object "**TDDUITaskAction**" as TDDUITaskAction_partOf #d9d9d9 {
    Action
}

map "**PrestationProjetPersonnalise : TDDUITaskPrestation**" as PrestationProjetPersonnalise #ccebc5 {
    idPrestation => identifier
    statutPrestation.statut => status
    statutPrestation.dateStatut => meta.lastUpdated
    statutPrestation.auteur => <&plus> auteurStatut
    descriptionPrestation => description
    titrePrestation => <&layers> input:titre
    typePrestation => <&layers> input:typePrestation
    evaluationPrestation => <&layers> input:evaluation
    pieceJointePrestation => <&layers> input:pieceJointe
    executionPeriod *-> executionPeriod
}

PrestationProjetPersonnalise -u-> TDDUICarePlanProjetPersonnalise_basedOn : basedOn
PrestationProjetPersonnalise -d-> TDDUITaskAction_partOf : partOf

@enduml