@startuml

hide empty methods

class TDDUIPatient_TDDUIPatientINS #LightPink
class TDDUIGoalAttente #LightGray
class TDDUIServiceRequestBesoin #LightGray
class TDDUIGoalObjectif #LightGray
class TDDUITaskAction #LightGray
class TDDUITaskMoyenRessource #LightGray
class TDDUITaskPrestation #LightGray
class TDDUITaskBilan #LightGray
class TDDUICarePlanProjetPersonalise #LightGray

TDDUIPatient_TDDUIPatientINS <-- TDDUICarePlanProjetPersonalise : CarePlan.subject

TDDUICarePlanProjetPersonalise <-- TDDUIServiceRequestBesoin : ServiceRequest.basedOn
TDDUICarePlanProjetPersonalise <-- TDDUIGoalObjectif : Goal.extension[TDDUICarePlanProjetPersonalise]
TDDUICarePlanProjetPersonalise <-- TDDUITaskAction : task.basedOn
TDDUICarePlanProjetPersonalise <-- TDDUITaskMoyenRessource : task.basedOn

TDDUIServiceRequestBesoin <- TDDUIGoalObjectif : TDDUIServiceRequestBesoin.addresses
TDDUIGoalObjectif <- TDDUITaskAction : TDDUITaskAction.input
TDDUITaskAction <- TDDUITaskMoyenRessource : TDDUITaskMoyenRessource.partOf

TDDUITaskAction <-- TDDUITaskPrestation : TDDUITaskPrestationProjetPerso.partOf
TDDUICarePlanProjetPersonalise <- TDDUITaskPrestation : task.basedOn

TDDUICarePlanProjetPersonalise <- TDDUITaskBilan : task.basedOn
TDDUIGoalAttente -> TDDUICarePlanProjetPersonalise : Goal.extension[TDDUICarePlanProjetPersonalise]

@enduml