@startuml

map "period" as period #back:WhiteSmoke;header:LightGray {
    dateEntree => start
    dateSortie => end
}

object "**TDDUIPatient/TDDUIPatientINS**" as TDDUIPatient #fdb462 {
    Usager
}

object "**TDDUIOrganization**" as TDDUIOrganization #bebada {
    ESSMSAccueil
    ESSMSProvenance
}

map "**Sejour : TDDUIEncounterSejour**" as Sejour #back:AliceBlue;header:LightSkyBlue {
    dateEntreePrevisionnelle => <&plus> TDDUI-plannedStartDate-r5
    dateSortiePrevisionnelle => <&plus> TDDUI-plannedEndDate-r5
    dateAdmission => <&plus> TDDUIAdmissionDate
    dateEntreeESSMSProvenance => <&plus> TDDUIEntryDateOrigin
    libelleModeEntree => <&plus> TDDUIEntryModelabel
    libelleModeSortie => <&plus> TDDUIExitModeLabel
    commentaire => <&plus> TDDUIComment
    idSejour => <&layers> identifier:idStay
    numeroDossierAdministratifSejour => <&layers> identifier:AdministrativeFileNumber
    numeroDossierESSMSProvenance => hospitalization.preAdmissionIdentifier
    modaliteAccueil => serviceType
    origineDemande => participant.individual.display
    period *-> period
}

Sejour -u-> TDDUIPatient : subject
Sejour -d-> TDDUIOrganization : serviceProvider\n hospitalization.origin

@enduml