@startuml

map "name" as name #DarkGray {
    nomNaissance => family
    prenom => given
    civilite => prefix
}

map "**Contact : TDDUIRelatedPersonContact**" as Contact #fccde5 {
    paysNationalite => <&plus> nationality
    commentaire => <&plus> comment
    description => <&plus> description
    identifiantPP => identifier
    role => <&layers> relationship:Role
    relation => <&layers> relationship:RelationType / <&layers> relationship:LegalProtection
    telecommunication => telecom
    sexe => gender
    dateNaissance => birthDate
    adresse => address
    name *-> name
}


@enduml