@startuml

object Usager #LightBlue

package Administratif as Admin #LightPink {
  object "Droit sociaux et de santé" as droit #LightPink
  object "Autorisations administratives" as autorisation #LightPink
  object "Identification et coordonnées" as id #LightPink
  object "Environnement et ressources" as env #LightPink
  object "Séjour" as sejour #LightPink
}

droit -[hidden]- autorisation
autorisation -[hidden]- id
id -[hidden]- env
env -[hidden]- sejour


package "Coordination des acteurs" as Coord #PaleGreen {
  object "Traçabilité des échanges" as traca #PaleGreen
  object "Agenda" as agenda #PaleGreen
  object "Présence / Absence" as pres #PaleGreen
  object "GED" as ged #PaleGreen
}

traca -[hidden]- agenda
agenda -[hidden]- pres
pres -[hidden]- ged


package "Accompagnement" as Acc #LightYellow {
  object "Cahier de liaison" as cahier #LightYellow
  object "Evaluation" as eval #LightYellow
  object "Parcours" as parc #LightYellow
  object "Projet personnalisé" as projP #LightYellow
}

cahier -[hidden]- eval
eval -[hidden]- parc
parc -[hidden]- projP


package "Soins" as Soin #Thistle {
  object "Maladies et sujets de santé" as mal #Thistle 
  object "Autonomie/invalidité" as autonomie #Thistle
  object "Antécedents de grossesse" as antG #Thistle
  object "Traitement" as trait #Thistle
  object "Hospitalisation et chirurgies" as hospi #Thistle
  object "Antécédents familiaux" as antF #Thistle
  object "Vaccination" as vac #Thistle
  object "Mesures" as mes #Thistle
  object "Habitudes de vie" as hab #Thistle
  object "Dernières volontés" as vol #Thistle
  object "Historique des soins" as histo #Thistle
  object "Ordonnances et prescriptions" as ord #Thistle
  object "Projet de soins personnalisé" as projS #Thistle
  object "Plan de soin" as plan #Thistle
  object "Alertes" as alerte #Thistle
  object "Allergies" as allergie #Thistle
  object "Observations soins" as obs #Thistle

}

hospi -[hidden]- ord
ord -[hidden]- projS
projS -[hidden]- mal
mal -[hidden]- antG
antG -[hidden]- antF

histo -[hidden]- autonomie
autonomie -[hidden]- obs
obs -[hidden]- vol
vol -[hidden]- hab
hab -[hidden]- plan

vac -[hidden]- trait
trait-[hidden]- allergie
allergie -[hidden]- mes
mes -[hidden]- alerte


Usager -- Admin
Usager -- Coord
Usager -- Acc
Usager -- Soin

@enduml