@startuml

object Usager #LightBlue

package Administratif as Admin #LightPink {
  object "Données A" as a #LightPink
  object "Données B" as b #LightPink
  object "Données C" as c #LightPink
}

a -[hidden]- b
b -[hidden]- c

package "Accompagnement" as Acc #LightYellow {
  object "Évaluation" as eval #LightYellow
  object "Projet personnalisé" as proj #LightYellow
}

eval -[hidden]- proj

Usager -- Admin
Usager -- Acc

@enduml
